afaqurk/linux-dash

README.md
=> Update go command

index.html
After a little thought I decided a merge was the best way of pulling this back.
I was also able to recover a some more history from Github because they store the pull requests as references in your repo. As I used merge, all those references are still valid, also everyone should be able to fast-forward.
There were a couple of commits I couldn't fetch; but I think the cherry (-pick) on top got that change. You should check to make sure that other cherries haven't been lost in the old history and pick them out if necessary.
=> Ka-thump history.

python-server.py
Very simple realization of python web server (only "out-of-box" components). I think that it's will be helpfull (not all users have Go or node.js in his localhost).
=> Added a very simple (and free of additional components) python webserver

python-server.py
After this patch server can handle request asynchronously. And in an modules "loader" used absolute path - it's provides ti run server from different directories.
=> Add threading in python webserver

js/modules.js
Added scope.delay = 2000; to let it appear a lot smoother.
=> added delay for network charts

css/theme-old.css
In the old theme the canvas should have a width of 100%.
Correct me if I'm wrong.
=> fixed width of canvas in old theme

js/modules.js, server/modules/shell_files/pm2.sh, templates/sections/applications.html
Added pm2 angular directive as table to application tab.
Added pm2 shell script.
Assumes pm2, awk  are both in path.
=> Pm2 added to application tab

server/modules/shell_files/ping.sh
Fix for https://github.com/afaqurk/linux-dash/issues/358
=> Fix ping module (https://github.com/afaqurk/linux-dash/issues/358)

server/modules/shell_files/cron_history.sh, server/modules/shell_files/scheduled_crons.sh
Add quotes escaping for fix cron scripts (https://github.com/afaqurk/linux-dash/issues/365)
=> Add quotes escaping for cron scripts

server/modules/shell_files/ip_addresses.sh
I have much global changes of main command in this PR. First, it fix subject issue(https://github.com/afaqurk/linux-dash/issues/354). Second, style of my ifconfig results (in Debian and last RHEL) look like this "inet 127.0.0.1" (not "inet addr:127.0.0.1"), and i have added the necessary changes in the "search string". As result my code is such different with an exist.
=> Fix iface aliases (https://github.com/afaqurk/linux-dash/issues/354)

js/modules.js, server/modules/shell_files/docker_processes.sh, templates/sections/system-status.html
It would be possible to use docker ps and docker top with
--format, but that's not compatible with docker 1.6, e.g. ubuntu 14.04 LTS.
=> add docker processes table

index.html, js/modules.js, server/modules/shell_files/cpu_temp.sh, templates/modules/cpu-temp.html, templates/sections/system-status.html
Hi, I try to add a basic view and parse the CPU temperature from lm-sensors
Look like this http://i.imgur.com/V5Gbz1I.png
now is able to parse some intel CPU and AMD CPU, I think it would depends on the sensors in MB.
And in order to print ° (&deg), I add charset=UTF-8 in index.html, I'm not sure what it would affect, so I note here.
Thank you!
=> Add a basic support for parsing CPU temperature from lm-sensors

server/modules/shell_files/download_transfer_rate.sh, server/modules/shell_files/upload_transfer_rate.sh
The script does the following:
1. Read first values for all interfaces and store them in an array
2. Sleep once. I even decreased the time to half a second.
3. Get second values and do the calculation.
=> speed up transfer rate script

bin/linux-dash, package.json, server/index.js
A minimal changes to make the package to run and configured as a global.
```
npm i -g https://github.com/noygal/linux-dash.git#feature/bin
export PORT=8080
linux-dash
```
=> added bin support + port from env variable

README.md
just noticed that when trying to quickly launch this for a try.
nice it is btw !!
=> README: fix python port # change doc

README.md, server/index.js
Hi there,
First of all, thanks for this great piece of software! I didn't find that handy to edit sources to change the Express port. Now, you can do that on the fly with the `PORT` env var.
Have a nice day.
=> Custom Express port with an environment variable

js/modules.js, server/modules/shell_files/current_ram.sh
Fixed typo and removed use of deprecated backquote commands in current ram script.
=> Fixes #411

app/server/linux_json_api.sh
- Add globals for all commonly used commands.  
- Removeall hard coded paths.
- Make function variables `local`.
Hardcoded paths make me shudder.  :). I did a little general cleanup and plan on doing a bit more.
Also, there was a mixed bag of `which` and `command -v`.  `Which` can be a bit flaky depending on where you're running it.  `command -v` is POSIX compliant but since your shebang is `/bin/bash` I used `type -P `
=> General cleanup for the linux_json_api.sh

app/server/index.py
I updated the reference to linuxDash.min.css! 👍
=> Fixes issue 435 - Linux-dash not working when python is use.

app/server/linux_json_api.sh
Updated as per @whw3's suggestion in https://github.com/afaqurk/linux-dash/issues/426.
Works perfectly on my raspberry pi 2.
=> Fix issue 426.  Adds ability to read raspberry pi temperature readings

ecosystem.config.js
this allows easy running of linux-dash with the node.js PM2 process manager.
=> added ecosystem file for PM2
